version: "3.8"

services:
  backend:
    build: .
    env_file:
      - .env
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    command: air -c .air.toml
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
